name: auth
description: "A new Flutter package project."
version: 0.0.1
publish_to: none

resolution: workspace

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # Shared
  core:
    path: ../../shared/core
  ui:
    path: ../../shared/ui
  database:
    path: ../../shared/database

  # State Management
  bloc: ^9.0.1
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7

  # Navigation
  go_router: ^16.2.4

  # DI
  get_it: ^8.2.0
  injectable: ^2.5.1

  # Utilities
  dartz: ^0.10.1
  json_annotation: ^4.9.0
  dio: ^5.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  bloc_test: ^10.0.0
  mocktail: ^1.0.4
  build_runner: ^2.7.1
  injectable_generator: ^2.8.1
  json_serializable: ^6.11.1
