name: syncing
description: "Sync feature for syncing data with server"
version: 0.0.1
publish_to: none

resolution: workspace

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # Shared
  core:
    path: ../../shared/core

  # Features
  notes:
    path: ../notes
  progress:
    path: ../progress
  points:
    path: ../points
  settings:
    path: ../settings

  # State Management
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7

  # DI
  get_it: ^8.2.0
  injectable: ^2.5.1

  # Utilities
  dartz: ^0.10.1

  device_info_plus: ^12.1.0
  dio: ^5.9.0
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.7.1
  injectable_generator: ^2.8.1
