name: noteventure
description: "Noteventure mobile application"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Shared packages
  core:
    path: ../../packages/shared/core
  ui:
    path: ../../packages/shared/ui
  database:
    path: ../../packages/shared/database

  # Feature packages
  notes:
    path: ../../packages/features/notes
  challenges:
    path: ../../packages/features/challenges
  points:
    path: ../../packages/features/points
  progress:
    path: ../../packages/features/progress
  achievements:
    path: ../../packages/features/achievements
  chaos:
    path: ../../packages/features/chaos
  themes:
    path: ../../packages/features/themes

  #  State management
  flutter_bloc: ^9.1.1

  #  Navigation
  go_router: ^16.2.4

  # DI
  get_it: ^8.2.0
  injectable: ^2.5.1

  # Audio
  audioplayers: ^6.5.1
  just_audio: ^0.10.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.7.1
  injectable_generator: ^2.8.1
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/sounds/
    - assets/lottie/
    - assets/fonts/
