name: database
description: "A new Flutter package project."
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  # Internal
  core:
    path: ../core

  # Database
  drift: ^2.28.2
  # sqlite3_flutter_libs: ^0.5.38
  drift_flutter: ^0.2.7
  path_provider: ^2.1.5
  path: ^1.9.1

  # DI
  get_it: ^8.2.0
  injectable: ^2.5.1
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  drift_dev: ^2.28.3
  build_runner: ^2.7.1
  injectable_generator: ^2.8.1
